name: Build and Deploy Expo App

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install Dependencies
        run: npm install

      - name: Build Android APK
        run: expo build:android --no-publish --non-interactive

      - name: Upload APK to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/*.apk
          tag: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Web Version
        run: |
          expo build:web --no-publish --non-interactive
          mv web-build dist

      - name: Deploy Web Version to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        run: |
          echo "Web app deployed to GitHub Pages"
